### ISSUE TITLE
Index out of bounds error when evaluating Mistral-7b-instruct-v0.2 on some instances of MMLU

### ISSUE THREAD

**Issue by ShadowTinker** [RUCAIBox/LLMBox#217]
Thank you for sharing this excellent repository. I believe that LLMBox has the potential to significantly enhance and facilitate the work of the research community.

However, I met an index out of bounds error when evaluating Mistral-7b-instruct-v0.2 on some instances of MMLU

Here is the command:
```shell
export CUDA_VISIBLE_DEVICES=1
python inference.py \
    -m /XXXX/models/Mistral-7B-Instruct-v0.2 \
    --model_type instruction \
    --model_backend huggingface \
    --vllm True \
    -d mmlu \
    --num_shots 5 \
    -b 20 \
    --no_flash_attention \
```

I notice that only the llama and ChatGPT families are included in `test.sh`, and llama-2-7b is indeed performing correctly. So I would like to ask if you have tested Mistral-7b-instruct-v0.2? If so, what are the corresponding commands?

The index out of bound error occurs when the progress bar shows 429/14042 (Omiting some previous output): 

```
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [121,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [122,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [13,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
mmlu:international_law:   3%|█▏                                      | 429/14042 [00:24<13:02, 17.40 instances/s]
2024-05-07 19:02:27 INFO Finished at 429 instances after 00:23.
Traceback (most recent call last):
  File "/zhdd/home/XXXX/Projects/LLMBox/inference.py", line 13, in <module>
    main()
  File "/zhdd/home/XXXX/Projects/LLMBox/inference.py", line 9, in main
    evaluator.evaluate()
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/utils/catch_error.py", line 15, in wrapper
    raise e
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/utils/catch_error.py", line 11, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/evaluator.py", line 82, in evaluate
    batch_results = call_model(batch)
                    ^^^^^^^^^^^^^^^^^
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/utils/batch_sampler.py", line 160, in call_model
    return self._forward_call(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/model/huggingface_model.py", line 449, in get_ppl
    prefix_cache = self.get_cache(
                   ^^^^^^^^^^^^^^^
  File "/zhdd/home/XXXX/Projects/LLMBox/utilization/model/huggingface_model.py", line 360, in get_cache
    results = self.model(
              ^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 1158, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 1043, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 757, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 654, in forward
    key_states = self.k_proj(hidden_states)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXXX/miniconda3/envs/LLMBox/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

```

**Comment by huyiwen** [comment]
It seems there is an issue with prefix caching; we will check it out in a bit

**Comment by huyiwen** [comment]
Please try our latest PR #222.
