### ISSUE TITLE
Cannot load C-Eval from local directory

### ISSUE THREAD

**Issue by xansar** [RUCAIBox/LLMBox#220]
I downloaded the C-Eval hub and wanted to load it from the local path. However, a bug occurred and indicated that there did not exist 'ceval':
```
Traceback (most recent call last):
  File "/data/home/XXXX/codes_repo/HealLLM/LLMBox/inference.py", line 13, in <module>
    main()
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/inference.py", line 8, in main
    evaluator = Evaluator(args)
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/evaluator.py", line 38, in __init__
    self.dataset = load_datasets(self.dataset_args, self.model)
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/utils/catch_error.py", line 23, in wrapper
    raise e
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/utils/catch_error.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/load.py", line 232, in load_datasets
    datasets.extend(load_dataset(d, args, model, args.dataset_threading))
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/load.py", line 185, in load_dataset
    dataset_name + ":" + first_dataset, dataset_cls(dataset_name, args, model, first_dataset)
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/dataset.py", line 165, in __init__
    self.load_raw_dataset(
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/dataset.py", line 330, in load_raw_dataset
    self.evaluation_data = list(load_fn(evaluation_set))
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/utils.py", line 306, in informative_load_fn
    return load_fn(split=split)
  File "/data/home/XXXX/codes_repo/HealthLLM/LLMBox/utilization/dataset/utils.py", line 244, in load_fn
    return ds.load_dataset(
  File "/data/home/XXXX/miniconda3/envs/llmbox/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/data/home/XXXX/miniconda3/envs/llmbox/lib/python3.10/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/data/home/XXXX/miniconda3/envs/llmbox/lib/python3.10/site-packages/datasets/load.py", line 1904, in dataset_module_factory
    raise e1 from None
  File "/data/home/XXXX/miniconda3/envs/llmbox/lib/python3.10/site-packages/datasets/load.py", line 1850, in dataset_module_factory
    raise DatasetNotFoundError(
datasets.exceptions.DatasetNotFoundError: Dataset 'ceval' doesn't exist on the Hub or cannot be accessed. If the dataset is private or gated, make sure to log in with `huggingface-cli login` or visit the dataset page at https://huggingface.co/datasets/ceval to ask for access.

```
The dataset structure is under the parent directory (LLMBox):
![image](https://github.com/RUCAIBox/LLMBox/assets/84836744/529139ad-e1e2-4513-9a6d-6e7825c23aab)

My command is:
```
python inference.py 
    -m /data/home/XXXX/.model/Qwen/Qwen1.5-1.8B 
    -d ceval:basic_medicine,clinical_medicine,physician 
    --dataset_path /data/home/XXXX/codes_repo/HealthLLM/LLMBox/datasets/ 
    --log_level debug 
    --evaluation_set "val" 
    --seed 42 
    --vllm True 
    --model_type base 
    --model_backend huggingface
```
I tried `....../LLMBox/datasets/`, `....../LLMBox/datasets/ceval`, and `....../LLMBox/datasets/ceval/ceval-exam`. None of the aforementioned paths worked.
The code could be executed successfully if I set the path to the CSV file, but it was inconvenient when I wanted to infer on several sub-datasets.

Due to the network constraint, I cannot download the dataset directly from the huggingface hub.

**Comment by huyiwen** [comment]
The error occurs because the `ceval-exam` dir is not in Hugging Face format, which typically includes a `dataset_infos.json` or `dataset_info.json` file. The original format may behave differently from the Hugging Face format, particularly in terms of dictionary keys or config_names.

For your issue, you have two options:

1. Convert the dataset into HuggingFace format by using [`save_to_disk`](https://huggingface.co/docs/datasets/v2.19.0/en/package_reference/main_classes#datasets.Dataset.save_to_disk) and then use the saved version.
2. Pull the latest updates #221 , and modify the `ceval-exam.py` file as follows:
```
# _URL = r"https://huggingface.co/datasets/ceval/ceval-exam/resolve/main/ceval-exam.zip"
_URL = r"ceval-exam.zip"
```

**Comment by huyiwen** [comment]
We now support `--hf_mirror` flag, which can resolve most network issues.
